### ISSUE TITLE
手机顶部菜单栏，自动旋转按钮关闭后被自动打开

### ISSUE THREAD

**Issue by songtangjie** [WeTestQuality/WeAutomator-docs-examples#7]
1. 先手工关闭顶部下拉菜单栏“自动旋转”按钮
2. 在wa启动运行测试
3. 下拉菜单栏，发现“自动旋转”按钮被打开

出现设备1：Oppo Find X，型号：PEUM00，Android 12
出现设备2：Oppo  一加ACE，型号 ：PGKM10，Android 12
测试用例场景：随意用例

**Comment by songtangjie** [comment]
出现设备1：Oppo Find X，安卓11系统

**Comment by Yezhj1** [comment]
用户问题记录视频：
https://user-images.githubusercontent.com/102509923/187340148-d7a1d959-bd87-4f77-a30f-dc8a097c3675.mp4

**Comment by Yezhj1** [comment]
在使用wea启动app时，比如拉起手机中的设置`start_app('com.android.settings')`，start_api会发送以下指令：

```
adb shell monkey -p com.android.settings -c android.intent.category.LAUNCHER 1
```
这条指令用于启动指定app，实际测试发现，它会打开Android手机的“自动旋转”按钮。用户可以单独使用本条指令测试。
